version: 1
disable_existing_loggers: False
formatters:
    standard:
      format: "%(asctime)s - %(levelname)s - %(message)s"
handlers:
  console:
    class: logging.StreamHandler
    level: WARNING
    formatter: standard
  file:
    class: logging.FileHandler
    level: DEBUG
    formatter: standard
    encoding: utf8

root:
  level: INFO
  handlers: [console, file]
